class Sample
  def int: () -> Integer
  def str: () -> String
  def ary: () -> Array[String]
  def record: () -> { int: Integer, str: String }
end

class SampleCollection
  include Enumerable[Sample]
  def each: () { (Sample) -> void } -> self
end
